addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.5.1")
addSbtPlugin("com.geirsson"       %  "sbt-scalafmt"          % "1.5.1")
addSbtPlugin("net.virtual-void"   %  "sbt-dependency-graph"  % "0.9.0")
addSbtPlugin("com.github.gseitz"  %  "sbt-release"           % "1.0.9")
addSbtPlugin("pl.project13.scala" %  "sbt-jmh"               % "0.3.4")